---
- name: Check if Docker is installed
  become: yes
  command: docker -v
  register: docker_installed
  ignore_errors: true

- name: Download docker installation file
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: /root/get-docker.sh
  when: docker_installed.failed

- name: Install Docker
  become: yes
  ansible.builtin.command:
   cmd: bash /root/get-docker.sh
  when: docker_installed.failed
